Various fixes open qasm reader
qsharp-community/qsharp-integrations pull request #14
Opened 2021-08-05 09:15 UTC by shahakL

This is the same as the closed #11

2021-08-06 18:09 UTC, RolfHuisman commented
Build is failing, because the sources are still using the old syntax. Currently have a merge request in the LCM branch which fixes this.

2021-08-06 18:12 UTC, RolfHuisman reviewed
Seems correct, but we first need to update package.
Also; we need a better way of doing the case insesitive search. cX for e.g. is missing.

2021-08-06 18:12 UTC, RolfHuisman commented on src/OpenQasmReader/Parser.cs
> +                    outside.AppendFormat("use {0} = Qubit[{1}] {{\n", qubitRegister.Key, qubitRegister.Value);
This also need an update of the buildpackages. Will do that in the LCM package

2021-08-07 14:28 UTC, RolfHuisman requested changes
Generates incorrect syntax of "use".

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Gates.qs
> +        use q = Qubit[3] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on src/OpenQasmReader/Parser.cs
> +                    outside.AppendFormat("use {0} = Qubit[{1}] {{\n", qubitRegister.Key, qubitRegister.Value);
Is incorrect. Will give "use q = Qubit[3] { " instead of the correct "use q = Qubit[3];".

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Bv3.qs
> +        use q = Qubit[5] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/CNot.qs
> +        use q = Qubit[2] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/FiveQubit1.qs
> +        use q = Qubit[5] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Hadamard.qs
> +        use q = Qubit[1] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Hid3.qs
> +        use q = Qubit[5] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Marg5.qs
> +        use q = Qubit[5] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-07 14:28 UTC, RolfHuisman commented on tests/OpenQasmReader.Tests/Validate/Toff6.qs
> +        use q = Qubit[5] {
Not correct syntax. Needs to be use q = Qubit[3]; instead of between braces.

2021-08-08 11:12 UTC, jond01 commented
Hi @RolfHuisman :)
Thanks for your review!
The `.qs` files' style here may not be the nicest, but I think the syntax is correct (the Q# code compiles).
Anyway, the style in #16 is better (and this PR's branch is merged into #16's branch), so I guess we can close this PR.

2021-08-26 17:28 UTC, crazy4pi314 commented
Sounds good, I'll close this and review/merge the other PR :)

2021-08-26 17:28 UTC, closed without merging